title: Siang
description: >- # this means to ignore newlines until "baseurl:"
  Siang Lim - personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.siang.ca" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
include: ["_posts"]